defaults:
  - model: sahcc
  - matcher: sah
  - data: shha
  - trainer: default
  - optimizer: adamw
  - scheduler: steplr
  - eval: default
  - _self_

seed: 42
project_name: sahcc
run_name: ${data.name}_${now:%Y%m%d_%H%M%S}

paths:
  log_dir: ./logs
  ckpt_dir: ./weights

hydra:
  job:
    chdir: false
